
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package toy3;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CHAR_CONST = 57;
  public static final int ASSIGNDECL = 39;
  public static final int CHAR = 21;
  public static final int GE = 41;
  public static final int DOUBLE_CONST = 55;
  public static final int DOUBLE = 19;
  public static final int SEMI = 5;
  public static final int INT = 17;
  public static final int OUT = 50;
  public static final int INIT = 16;
  public static final int RBRAC = 13;
  public static final int REF = 52;
  public static final int MINUS = 35;
  public static final int FOR = 14;
  public static final int RED = 25;
  public static final int OUTNL = 51;
  public static final int AND = 47;
  public static final int NOT = 46;
  public static final int LT = 42;
  public static final int RPAR = 11;
  public static final int IN = 49;
  public static final int OR = 48;
  public static final int BOOL = 18;
  public static final int COMMA = 7;
  public static final int DIV = 37;
  public static final int BEGIN = 3;
  public static final int PLUS = 34;
  public static final int ASSIGN = 38;
  public static final int IF = 29;
  public static final int ID = 58;
  public static final int LE = 43;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int INT_CONST = 54;
  public static final int TRUE = 23;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int PIPE = 53;
  public static final int EQ = 44;
  public static final int RGB = 22;
  public static final int TIMES = 36;
  public static final int COLON = 6;
  public static final int ELSE = 31;
  public static final int WHILE = 32;
  public static final int THEN = 30;
  public static final int NE = 45;
  public static final int BLUE = 27;
  public static final int IDEF = 9;
  public static final int END = 4;
  public static final int LPAR = 10;
  public static final int STRING = 20;
  public static final int DEF = 8;
  public static final int LBRAC = 12;
  public static final int GREEN = 26;
  public static final int FALSE = 24;
  public static final int STRING_CONST = 56;
  public static final int GT = 40;
  public static final int DO = 33;
  public static final int STEP = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "BEGIN",
  "END",
  "SEMI",
  "COLON",
  "COMMA",
  "DEF",
  "IDEF",
  "LPAR",
  "RPAR",
  "LBRAC",
  "RBRAC",
  "FOR",
  "STEP",
  "INIT",
  "INT",
  "BOOL",
  "DOUBLE",
  "STRING",
  "CHAR",
  "RGB",
  "TRUE",
  "FALSE",
  "RED",
  "GREEN",
  "BLUE",
  "RETURN",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "ASSIGN",
  "ASSIGNDECL",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "NOT",
  "AND",
  "OR",
  "IN",
  "OUT",
  "OUTNL",
  "REF",
  "PIPE",
  "INT_CONST",
  "DOUBLE_CONST",
  "STRING_CONST",
  "CHAR_CONST",
  "ID"
  };
}

